name = "Trainworld"
version = "5.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f82e1e5c745b7ef776f500a6a9ee7156868c03cef5faccae2a359a3ffedf758"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
