name = "Trainworld"
version = "5.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d0511b66feb19566bffee9bc1b2fb8c32ab3920ed856f99e2f51d0b77754e36"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
