name = "Trainworld"
version = "5.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0594a3492745baef7c072aafff4ab540fb75ac60df8e54c107ef15ced7a51bee"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
