name = "Trainworld"
version = "5.1.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19e4344ef0e813ef85d43ce8a225855f2d27f30a553a3e81a7cb64cb5377e567"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
