name = "Trainworld"
version = "5.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb6dc409d2831ffddc92dc6a1e4aecab70bc4675a66f3ae2710af3deaf282d07"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
