name = "Trainworld"
version = "5.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d0abe70b58c71fb63e25f1800f5d17fdfdd969d5d226462982e27524e1d532b"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
