name = "Trainworld"
version = "5.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed7e94d041cedb04022da97bbf5af4d3c0ab936653517d38c54718ee5a5bd2e4"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
