name = "Trainworld"
version = "5.1.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e4fbf541dc90f62bbf78cc55ffbddc7e0c094fa99ed5cd5267f4dc9a470841e"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
