name = "Trainworld"
version = "5.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "633793025e4bc17de2a488be4f56ed79d7ff0609ad0a2898cb840f82a13d84aa"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
