name = "Trainworld"
version = "5.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "312139bc5e81c7fa7378c758ff667e795669ed62c41caacc6e41b66a353e92a0"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
