name = "Trainworld"
version = "5.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52a3fcebf0c634db01cd9efcd42362062f19d9a863a9549c47acfa00699dcdac"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
