
#General Config Section
[general]
	#The Application ID of the Discord App to use
	clientID = 972803325189849108
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = true
	#Enable/Disable the in game config screen
	configScreen = true
	#Display the icon2048 and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = true
	#Internal Version Number. NO TOUCHY!
	version = 13

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Minecraft is loading"
	#The second line of text under the app name
	state = "Rude Mixins getting applied to other mods."
	#The Asset ID of the image to display as the large image
	largeImageKey = "icon2048"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but with trains. And other shit. Cuz we ain't those trainspot mfs. Don't @ me."
	#The Asset ID of the image to display as the small image
	smallImageKey = "icon2048"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	[[init.buttons]]
	    label = "Curseforge"
	    url = "https://www.curseforge.com/minecraft/modpacks/trainworld"
	    
#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is currently lazy"
	#The seconds line of text under the app name
	state = "Chilling in the menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = "icon2048"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but with trains. And other shit. Cuz we ain't those trainspot mfs. Don't @ me."
	#The Asset ID of the image to display as the small image
	smallImageKey = "icon2048"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	[[main_menu.buttons]]
	    label = "Curseforge"
	    url = "https://www.curseforge.com/minecraft/modpacks/trainworld"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a server"
	#The second line of text under the app name
	state = "Searching for friends"
	#The Asset ID of the image to display as the large image
	largeImageKey = "icon2048"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but with trains. And other shit. Cuz we ain't those trainspot mfs. Don't @ me."
	#The Asset ID of the image to display as the small image
	smallImageKey = "icon2048"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
[[server_list.buttons]]
    label = "Curseforge"
    url = "https://www.curseforge.com/minecraft/modpacks/trainworld"

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a Realm"
	#The second line of text under the app name
	state = "Browsing Realms"
	#The Asset ID of the image to display as the large image
	largeImageKey = "icon2048"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but with trains. And other shit. Cuz we ain't those trainspot mfs. Don't @ me."
	#The Asset ID of the image to display as the small image
	smallImageKey = "icon2048"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
[[realms_list.buttons]]
    label = "Curseforge"
    url = "https://www.curseforge.com/minecraft/modpacks/trainworld"

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is joining a game"
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID of the image to display as the large image
	largeImageKey = "icon2048"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but with trains. And other shit. Cuz we ain't those trainspot mfs. Don't @ me."
	#The Asset ID of the image to display as the small image
	smallImageKey = "icon2048"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
[[join_game.buttons]]
    label = "Curseforge"
    url = "https://www.curseforge.com/minecraft/modpacks/trainworld"

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Currently In %world%"
	#The second line of text under the app name
	state = "Playing lonely mode"
	#The Asset ID of the image to display as the large image
	largeImageKey = "icon2048"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but with trains. And other shit. Cuz we ain't those trainspot mfs. Don't @ me."
	#The Asset ID of the image to display as the small image
	smallImageKey = "icon2048"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
[[single_player.buttons]]
    label = "Curseforge"
    url = "https://www.curseforge.com/minecraft/modpacks/trainworld"

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %servername% with %players% players"
	#The second line of text under the app name
	state = "Playing online"
	#The Asset ID of the image to display as the large image
	largeImageKey = "icon2048"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but with trains. And other shit. Cuz we ain't those trainspot mfs. Don't @ me."
	#The Asset ID of the image to display as the small image
	smallImageKey = "icon2048"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
[[multi_player.buttons]]
    label = "Curseforge"
    url = "https://www.curseforge.com/minecraft/modpacks/trainworld"

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID of the image to display as the large image
	largeImageKey = "icon2048"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but with trains. And other shit. Cuz we ain't those trainspot mfs. Don't @ me."
	#The Asset ID of the image to display as the small image
	smallImageKey = "icon2048"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
[[realms.buttons]]
    label = "Curseforge"
    url = "https://www.curseforge.com/minecraft/modpacks/trainworld"

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Playing Minecraft"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "icon2048"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but with trains. And other shit. Cuz we ain't one of those trainspot mfs. Don't @ me."
	#The Asset ID of the image to display as the small image
	smallImageKey = "icon2048"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
[[generic.buttons]]
    label = "Curseforge"
    url = "https://www.curseforge.com/minecraft/modpacks/trainworld"

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "icon2048"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "icon2048"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "icon2048"
		smallImageText = "%mods% mods installed"
