name = "All Palms are Beautiful"
filename = "allpalmsarebeautiful-0.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3776/159/allpalmsarebeautiful-0.1.1.jar"
hash-format = "sha1"
hash = "130ea377a32ff2f1282efd3900967c8d1df06454"

[update]
[update.curseforge]
file-id = 3776159
project-id = 619119
