name = "Ars Nouveau"
filename = "ars_nouveau-1.16.5-1.25.1.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "be34522287e61f8d215f105696176ecbeab9266b"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3805021
project-id = 401955
