name = "Oh The Biomes You'll Go Plus"
filename = "abyg-1.2-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3432/455/abyg-1.2-forge.jar"
hash-format = "sha1"
hash = "786249e6d046960702042e99a773eab369be5543"

[update]
[update.curseforge]
file-id = 3432455
project-id = 488573
