name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.2.510.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "babf714e55d870802215621770826b0264411a89"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3794610
project-id = 239197
