name = "CraftPresence"
filename = "CraftPresence-Forge-1.16.5-Release-1.8.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3475/685/CraftPresence-Forge-1.16.5-Release-1.8.8.jar"
hash-format = "sha1"
hash = "19af70311552de1bec3ea01ab4b1bff9ff52c437"

[update]
[update.curseforge]
file-id = 3475685
project-id = 297038
