name = "Exchangers"
filename = "Exchangers-1.16.5-3.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3207/546/Exchangers-1.16.5-3.0.2.jar"
hash-format = "sha1"
hash = "0782af298f05382ba9f25e6e845298fe2535c351"

[update]
[update.curseforge]
file-id = 3207546
project-id = 270183
