name = "JAOPCA"
filename = "JAOPCA-1.16.5-3.4.3.26.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/879/JAOPCA-1.16.5-3.4.3.26.jar"
hash-format = "sha1"
hash = "496390dad4bda664c85316cc18f9bd7bae4662b0"

[update]
[update.curseforge]
file-id = 3681879
project-id = 266936
