name = "JEI Enchantment Info"
filename = "JEIEnchantmentInfo-1.16.5-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3751/428/JEIEnchantmentInfo-1.16.5-1.3.0.jar"
hash-format = "sha1"
hash = "802c0b94f8e0f0a8c2326510956ef3f71425047c"

[update]
[update.curseforge]
file-id = 3751428
project-id = 392748
