name = "MinecraftCapes Mod"
filename = "MinecraftCapes Forge 1.16.5-11.0.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3398/885/MinecraftCapes%20Forge%201.16.5-11.0.0.jar"
hash-format = "sha1"
hash = "19b4ff837e3e65b23f5494968599995abbf73965"

[update]
[update.curseforge]
file-id = 3398885
project-id = 359836
