name = "MineColonies"
filename = "minecolonies-1.16.5-1.0.763-ALPHA.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "05025e648eb4c1395d4b6b0aa789ea2b2a64ebdf"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3801436
project-id = 245506
