name = "MineColonies"
filename = "minecolonies-1.16.5-1.0.728-ALPHA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3788/773/minecolonies-1.16.5-1.0.728-ALPHA.jar"
hash-format = "sha1"
hash = "56a4eb019fdf2d7091839e4f962f3366d23e3ba2"

[update]
[update.curseforge]
file-id = 3788773
project-id = 245506
