name = "Performant"
filename = "performant-1.16.2-5-3.95m.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3768/985/performant-1.16.2-5-3.95m.jar"
hash-format = "sha1"
hash = "657cbaf2df82769ddcf82216bbaec94f24d3218e"

[update]
[update.curseforge]
file-id = 3768985
project-id = 354143
