name = "Performant"
filename = "performant-1.16.2-5-3.97m.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "8953001b282b99c57f2f83cd804cd08179e89dae"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3791080
project-id = 354143
