name = "Gauges and Switches"
filename = "rsgauges-1.16.5-1.2.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3729/770/rsgauges-1.16.5-1.2.15.jar"
hash-format = "sha1"
hash = "5f8f526c9b78d1f52e3154805e838fa762b563dd"

[update]
[update.curseforge]
file-id = 3729770
project-id = 296686
