name = "RFTools Builder"
filename = "rftoolsbuilder-1.16-3.1.9.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "969e8356dd99d52e8233a26160a37decc6d24253"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3786800
project-id = 347706
