name = "Right Click, Get Crops"
filename = "right_click_get_crops-1.16.5-1.0.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3554/754/right_click_get_crops-1.16.5-1.0.0.1.jar"
hash-format = "sha1"
hash = "47c388b5f675550894e7b65e136cd2982aac41bb"

[update]
[update.curseforge]
file-id = 3554754
project-id = 552442
