name = "Right Click, Get Crops"
filename = "right_click_get_crops-1.16.5-1.1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3780/501/right_click_get_crops-1.16.5-1.1.0.2.jar"
hash-format = "sha1"
hash = "508ed7432798cd403d2da57a6927e97633f9ea1b"

[update]
[update.curseforge]
file-id = 3780501
project-id = 552442
