name = "Simple Discord RPC [Forge/Fabric]"
filename = "simple-rpc-1.16.5-3.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3785/417/simple-rpc-1.16.5-3.0.1.jar"
hash-format = "sha1"
hash = "44259ee5df2f0c31697c8c529023c43042fd4df0"

[update]
[update.curseforge]
file-id = 3785417
project-id = 411816
