name = "Structurize"
filename = "structurize-1.16.5-1.0.403-ALPHA.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "854aea05d0bf483741392b7319de71ad17e61cad"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3789162
project-id = 298744
