name = "Traveler's Backpack"
filename = "TravelersBackpack-1.16.5-5.4.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/522/TravelersBackpack-1.16.5-5.4.7.jar"
hash-format = "sha1"
hash = "72d3b9126c62cc793618783085c40d4d27516462"

[update]
[update.curseforge]
file-id = 3667522
project-id = 321117
